# DecisionTree
# clang > 4 and gcc >= 7 is required
# Ubuntu 14.04
sudo: required
dist: trusty

# Enable C++ support
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER=g++-6
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: 
        - COMPILER=g++-7
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - COMPILER=g++-8
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode9.0
      compiler: clang
    - os: osx
      osx_image: xcode9.1
      compiler: clang
    - os: osx
      osx_image: xcode9.2
      compiler: clang
    - os: osx
      osx_image: xcode9.3
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      compiler: clang

before_install:
    - eval "${MATRIX_EVAL}"

# Build steps
script:
    - mkdir build && cd build
    - cmake ..
    - make -j10
    - cd ../test/ && mkdir build && cd build
    - cmake ..
    - make -j10
